# Generated by Django 5.2.1 on 2025-06-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('book_author', models.CharField(max_length=200)),
                ('book_publisher', models.CharField(max_length=200)),
                ('book_isbn', models.CharField(max_length=50, unique=True)),
                ('book_year', models.PositiveIntegerField()),
                ('book_thumbnail', models.ImageField(blank=True, null=True, upload_to='book_thumbnails/')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=200)),
                ('student_name', models.CharField(max_length=200)),
                ('student_contact', models.CharField(max_length=200)),
                ('student_address', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('student_ref_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
        ),
    ]
