# Generated by Django 5.2.1 on 2025-06-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbr_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_ref_id', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=100)),
                ('student_contact', models.CharField(max_length=15)),
                ('student_id', models.CharField(max_length=50)),
                ('book_name', models.CharField(max_length=255)),
                ('rental_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
            ],
        ),
    ]
